POST http://localhost:3000/api/login
Content-Type: application/json

{
   "username": "jane", "password": "Jane0908"
}

###
DELETE http://localhost:3000/api/users/1
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjQzNTcwMzA0fQ.bSO9qhrMUM6vVhCUIilRYeeWRUEwM6xidNEKatNuDvA

###
POST http://localhost:3000/api/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImphbmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjQzNjAwNTQ3fQ.D47G3JuRIHCpH0mUG1efKlMaSJDp7oT8EXcOVTQwwik"
}

###
POST http://localhost:3000/api/logout
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImphbmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjQzNjAwNTYxLCJleHAiOjE2NDM2MDE0NjF9.gtZ98lIDCPDxwwGeWKMLJ_UU6_In7bUprLnKnOw0NtY
Content-Type: application/json

{
    "token" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjIiLCJ1c2VybmFtZSI6ImphbmUiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjQzNjAwNTYxLCJleHAiOjE2NDM2MDE0NjF9.gtZ98lIDCPDxwwGeWKMLJ_UU6_In7bUprLnKnOw0NtY"
}